#!/bin/bash
#
# Start Cobalt Strike Team Server
#

# make pretty looking messages (thanks Carlos)

#################

clear
echo -e "\033[1;31m   _____         _             _  _    _____  _          _  _           \033[0m"
echo -e "\033[1;32m  /  __ \       | |           | || |  /  ___|| |        (_)| |          \033[0m"
echo -e "\033[1;33m  | /  \/  ___  | |__    __ _ | || |_ \ \`--. | |_  _ __  _ | | __  ___  \033[0m"
echo -e "\033[1;34m  | |     / _ \ | '_ \  / _\` || || __| \`--. \| __|| '__|| || |/ / / _ \ \033[0m"
echo -e "\033[1;35m  | \__/\| (_) || |_) || (_| || || |_ /\__/ /| |_ | |   | ||   < |  __/ \033[0m"
echo -e "\033[1;36m   \____/ \___/ |_.__/  \__,_||_| \__|\____/  \__||_|   |_||_|\_\ \___| \033[0m"   
echo -e "\033[1;34m   -------------- \033[0m"                           
echo -e "\033[1;31m __  __  ____                      \033[0m"
echo -e "\033[1;32m \ \/ / |  _ \   ___    ___    ___  \033[0m"
echo -e "\033[1;33m  \  /  | |_) | / __|  / _ \  / __| \033[0m"
echo -e "\033[1;34m  /  \  |  _ <  \__ \ |  __/ | (__  \033[0m"
echo -e "\033[1;35m /_/\_\ |_| \_\ |___/  \___|  \___| \n\033[0m"
echo -e "\033[1;34m   -------------- \033[0m"
echo -e "\033[1;31m  __          __   _____   _____     _____                \033[0m"
echo -e "\033[1;32m  \ \        / /  / ____| |  __ \   / ____|               \033[0m"
echo -e "\033[1;33m   \ \  /\  / /  | |  __  | |__) | | (___     ___    ___  \033[0m"
echo -e "\033[1;34m    \ \/  \/ /   | | |_ | |  ___/   \___ \   / _ \  / __| \033[0m"
echo -e "\033[1;35m     \  /\  /    | |__| | | |       ____) | |  __/ | (__  \033[0m"
echo -e "\033[1;36m      \/  \/      \_____| |_|      |_____/   \___|  \___|  \n\033[0m"
echo -e "\033[1;31m\tThank's 北美第一突破手 && WgpSec \n\033[0m"
echo -e "\033[1;32m\t[ help ] \n\033[0m"
echo -e "\033[1;35m\t[ https://github.com/wgpsec ] \033[0m"
echo -e "\033[1;34m\t[ https://mp.weixin.qq.com/s/6nBrRJHFFpCw4N90n8aURA ] \033[0m"
echo -e "\033[1;33m\t[ https://blog.zygd.site/CobaltStrike%204.2%20Cloud%20function%20and%20Docker.html ] \n\033[0m"



#################

function print_good () {
    echo -e "\x1B[01;32m[+]\x1B[0m $1"
}

function print_error () {
    echo -e "\x1B[01;31m[-]\x1B[0m $1"
}

function print_info () {
    echo -e "\x1B[01;34m[*]\x1B[0m $1"
}

# check that we're r00t
if [ $UID -ne 0 ]; then
        print_error "Superuser privileges are required to run the team server"
        exit
fi

# check if java is available...
if [ $(command -v java) ]; then
        true
else
        print_error "java is not in \$PATH"
        echo "    is Java installed?"
        exit
fi

# check if keytool is available...
if [ $(command -v keytool) ]; then
        true
else
        print_error "keytool is not in \$PATH"
        echo "    install the Java Developer Kit"
        exit
fi

# generate a certificate
        # naturally you're welcome to replace this step with your own permanent certificate.
        # just make sure you pass -Djavax.net.ssl.keyStore="/path/to/whatever" and
        # -Djavax.net.ssl.keyStorePassword="password" to java. This is used for setting up
        # an SSL server socket. Also, the SHA-1 digest of the first certificate in the store
        # is printed so users may have a chance to verify they're not being owned.
if [ -e /CobaltStrike/cobaltstrike.store ]; then
        print_info "Will use existing X509 certificate and keystore (for SSL)"
else
        print_info "Generating X509 certificate and keystore (for SSL)"
        IFS_BACKUP=$IFS
        IFS=$(echo -en "\n\b")
        keytool -keystore /CobaltStrike/cobaltstrike.store -storepass $passwd -keypass $passwd -genkey -keyalg RSA -alias "$aliasname" -dname "$dname"
        IFS=$IFS_BACKUP
fi
# start the team server.
java -XX:ParallelGCThreads=4 -Dcobaltstrike.server_port=$server_port -Djavax.net.ssl.keyStore=/CobaltStrike/cobaltstrike.store -Djavax.net.ssl.keyStorePassword=$passwd -server -XX:+AggressiveHeap -XX:+UseParallelGC -classpath /CobaltStrike/CobaltStrike.jar server.TeamServer $server_ip $passwd

